framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
        fallbacks:
            - en
    enabled_locales: ['fr', 'en', 'de', 'es', 'it', 'nl', 'pt', 'pl']
