<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260507000816 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE details_commandes DROP FOREIGN KEY `FK_4FD424F7806F0F5C`');
        $this->addSql('ALTER TABLE details_commandes DROP FOREIGN KEY `FK_4FD424F782EA2E54`');
        $this->addSql('DROP INDEX idx_details_commande ON details_commandes');
        $this->addSql('CREATE INDEX IDX_4FD424F782EA2E54 ON details_commandes (commande_id)');
        $this->addSql('DROP INDEX idx_details_equipement ON details_commandes');
        $this->addSql('CREATE INDEX IDX_4FD424F7806F0F5C ON details_commandes (equipement_id)');
        $this->addSql('ALTER TABLE details_commandes ADD CONSTRAINT `FK_4FD424F7806F0F5C` FOREIGN KEY (equipement_id) REFERENCES equipements (id)');
        $this->addSql('ALTER TABLE details_commandes ADD CONSTRAINT `FK_4FD424F782EA2E54` FOREIGN KEY (commande_id) REFERENCES commandes (id)');
        $this->addSql('ALTER TABLE equipements DROP FOREIGN KEY `fk_equipements_categorie`');
        $this->addSql('ALTER TABLE equipements DROP FOREIGN KEY `fk_equipements_fournisseur`');
        $this->addSql('DROP INDEX idx_equipements_categorie ON equipements');
        $this->addSql('DROP INDEX idx_equipements_fournisseur ON equipements');
        $this->addSql('ALTER TABLE equipements CHANGE description description LONGTEXT DEFAULT NULL, CHANGE quantite_stock quantite_stock INT NOT NULL, CHANGE seuil_alerte seuil_alerte INT NOT NULL, CHANGE disponible disponible TINYINT NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE equipements ADD CONSTRAINT FK_3F02D86BBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories (id)');
        $this->addSql('ALTER TABLE equipements ADD CONSTRAINT FK_3F02D86B670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (id)');
        $this->addSql('ALTER TABLE forum_moderation_alert DROP FOREIGN KEY `FK_9B2C69CF1E8FDE0`');
        $this->addSql('ALTER TABLE forum_moderation_alert DROP FOREIGN KEY `FK_9B2C69CFB88E14F`');
        $this->addSql('ALTER TABLE forum_moderation_alert CHANGE created_by created_by INT NOT NULL');
        $this->addSql('ALTER TABLE forum_moderation_alert ADD CONSTRAINT FK_64949EBCDE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_moderation_alert ADD CONSTRAINT FK_64949EBC16FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_64949EBCDE12AB56 ON forum_moderation_alert (created_by)');
        $this->addSql('CREATE INDEX IDX_64949EBC16FE72E1 ON forum_moderation_alert (updated_by)');
        $this->addSql('DROP INDEX idx_9b2c69cf1e8fde0 ON forum_moderation_alert');
        $this->addSql('CREATE INDEX IDX_64949EBCBA9CD190 ON forum_moderation_alert (commentaire_id)');
        $this->addSql('DROP INDEX idx_9b2c69cffb88e14f ON forum_moderation_alert');
        $this->addSql('CREATE INDEX IDX_64949EBCFB88E14F ON forum_moderation_alert (utilisateur_id)');
        $this->addSql('ALTER TABLE forum_moderation_alert ADD CONSTRAINT `FK_9B2C69CF1E8FDE0` FOREIGN KEY (commentaire_id) REFERENCES commentaire (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE forum_moderation_alert ADD CONSTRAINT `FK_9B2C69CFB88E14F` FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP FOREIGN KEY `FK_4B0E7C324584665A`');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP FOREIGN KEY `FK_4B0E7C32DB38439E`');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD updated_at DATETIME DEFAULT NULL, ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD CONSTRAINT FK_8D0F1179DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD CONSTRAINT FK_8D0F117916FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_8D0F1179DE12AB56 ON forum_post_bookmark (created_by)');
        $this->addSql('CREATE INDEX IDX_8D0F117916FE72E1 ON forum_post_bookmark (updated_by)');
        $this->addSql('DROP INDEX idx_4b0e7c32db38439e ON forum_post_bookmark');
        $this->addSql('CREATE INDEX idx_forum_post_bookmark_user ON forum_post_bookmark (utilisateur_id)');
        $this->addSql('DROP INDEX idx_4b0e7c324584665a ON forum_post_bookmark');
        $this->addSql('CREATE INDEX idx_forum_post_bookmark_post ON forum_post_bookmark (post_id)');
        $this->addSql('DROP INDEX idx_4b0e7c32c5f6b89b ON forum_post_bookmark');
        $this->addSql('CREATE INDEX idx_forum_post_bookmark_type ON forum_post_bookmark (bookmark_type)');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD CONSTRAINT `FK_4B0E7C324584665A` FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD CONSTRAINT `FK_4B0E7C32DB38439E` FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fournisseurs CHANGE adresse adresse LONGTEXT DEFAULT NULL, CHANGE actif actif TINYINT NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY `fk_locations_terrain`');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY `fk_locations_utilisateur`');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY `fk_locations_vehicule`');
        $this->addSql('DROP INDEX numero_location ON locations');
        $this->addSql('DROP INDEX idx_locations_utilisateur ON locations');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY `fk_locations_terrain`');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY `fk_locations_vehicule`');
        $this->addSql('ALTER TABLE locations CHANGE type_location type_location VARCHAR(20) NOT NULL, CHANGE caution caution NUMERIC(10, 2) NOT NULL, CHANGE statut statut VARCHAR(20) NOT NULL, CHANGE date_reservation date_reservation DATETIME NOT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT FK_17E64ABA50EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id)');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT FK_17E64ABA4A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicules (id)');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT FK_17E64ABA8A2D8B41 FOREIGN KEY (terrain_id) REFERENCES terrains (id)');
        $this->addSql('DROP INDEX idx_locations_vehicule ON locations');
        $this->addSql('CREATE INDEX IDX_17E64ABA4A4A3511 ON locations (vehicule_id)');
        $this->addSql('DROP INDEX idx_locations_terrain ON locations');
        $this->addSql('CREATE INDEX IDX_17E64ABA8A2D8B41 ON locations (terrain_id)');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT `fk_locations_terrain` FOREIGN KEY (terrain_id) REFERENCES terrains (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT `fk_locations_vehicule` FOREIGN KEY (vehicule_id) REFERENCES vehicules (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie ADD updated_by INT DEFAULT NULL, CHANGE nom nom VARCHAR(150) DEFAULT NULL, CHANGE created_by created_by INT NOT NULL');
        $this->addSql('ALTER TABLE maladie ADD CONSTRAINT FK_ADC4024BDE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie ADD CONSTRAINT FK_ADC4024B16FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_ADC4024BDE12AB56 ON maladie (created_by)');
        $this->addSql('CREATE INDEX IDX_ADC4024B16FE72E1 ON maladie (updated_by)');
        $this->addSql('ALTER TABLE maladie_case ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL, CHANGE maladie_id maladie_id INT DEFAULT NULL, CHANGE utilisateur_id utilisateur_id INT DEFAULT NULL, CHANGE symptomes symptomes LONGTEXT DEFAULT NULL, CHANGE statut statut VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE maladie_case ADD CONSTRAINT FK_2D08B4F4B4B1C397 FOREIGN KEY (maladie_id) REFERENCES maladie (id_maladie) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case ADD CONSTRAINT FK_2D08B4F4FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case ADD CONSTRAINT FK_2D08B4F4DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case ADD CONSTRAINT FK_2D08B4F416FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_2D08B4F4B4B1C397 ON maladie_case (maladie_id)');
        $this->addSql('CREATE INDEX IDX_2D08B4F4FB88E14F ON maladie_case (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_2D08B4F4DE12AB56 ON maladie_case (created_by)');
        $this->addSql('CREATE INDEX IDX_2D08B4F416FE72E1 ON maladie_case (updated_by)');
        $this->addSql('ALTER TABLE maladie_case_photo ADD updated_at DATETIME DEFAULT NULL, ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL, CHANGE case_update_id case_update_id INT DEFAULT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE maladie_case_photo ADD CONSTRAINT FK_EA6003FBB59A4A FOREIGN KEY (case_update_id) REFERENCES maladie_case_update (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case_photo ADD CONSTRAINT FK_EA6003DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case_photo ADD CONSTRAINT FK_EA600316FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_EA6003FBB59A4A ON maladie_case_photo (case_update_id)');
        $this->addSql('CREATE INDEX IDX_EA6003DE12AB56 ON maladie_case_photo (created_by)');
        $this->addSql('CREATE INDEX IDX_EA600316FE72E1 ON maladie_case_photo (updated_by)');
        $this->addSql('ALTER TABLE maladie_case_update ADD updated_at DATETIME DEFAULT NULL, ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL, CHANGE case_id case_id INT DEFAULT NULL, CHANGE resultat resultat VARCHAR(30) DEFAULT NULL, CHANGE commentaire commentaire LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE maladie_case_update ADD CONSTRAINT FK_1254A170CF10D4F5 FOREIGN KEY (case_id) REFERENCES maladie_case (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case_update ADD CONSTRAINT FK_1254A1701C0BE183 FOREIGN KEY (solution_id) REFERENCES solution_traitement (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE maladie_case_update ADD CONSTRAINT FK_1254A170DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE maladie_case_update ADD CONSTRAINT FK_1254A17016FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_1254A170CF10D4F5 ON maladie_case_update (case_id)');
        $this->addSql('CREATE INDEX IDX_1254A1701C0BE183 ON maladie_case_update (solution_id)');
        $this->addSql('CREATE INDEX IDX_1254A170DE12AB56 ON maladie_case_update (created_by)');
        $this->addSql('CREATE INDEX IDX_1254A17016FE72E1 ON maladie_case_update (updated_by)');
        $this->addSql('ALTER TABLE participations CHANGE id_evenement id_evenement INT DEFAULT NULL, CHANGE id_utilisateur id_utilisateur INT DEFAULT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE date_inscription date_inscription DATETIME NOT NULL, CHANGE nombre_accompagnants nombre_accompagnants INT NOT NULL, CHANGE commentaire commentaire LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT FK_FDC6C6E88B13D439 FOREIGN KEY (id_evenement) REFERENCES evenements (id_evenement)');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT FK_FDC6C6E850EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id)');
        $this->addSql('CREATE INDEX IDX_FDC6C6E88B13D439 ON participations (id_evenement)');
        $this->addSql('DROP INDEX id_utilisateur ON participations');
        $this->addSql('CREATE INDEX IDX_FDC6C6E850EAE44 ON participations (id_utilisateur)');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY `fk_post_utilisateur`');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY `fk_post_utilisateur`');
        $this->addSql('ALTER TABLE post ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL, CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE categorie categorie VARCHAR(255) DEFAULT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DDE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D16FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DDE12AB56 ON post (created_by)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D16FE72E1 ON post (updated_by)');
        $this->addSql('DROP INDEX fk_post_utilisateur ON post');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DFB88E14F ON post (utilisateur_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT `fk_post_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_reaction ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE post_reaction ADD CONSTRAINT FK_1B3A8E56DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_reaction ADD CONSTRAINT FK_1B3A8E5616FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_1B3A8E56DE12AB56 ON post_reaction (created_by)');
        $this->addSql('CREATE INDEX IDX_1B3A8E5616FE72E1 ON post_reaction (updated_by)');
        $this->addSql('ALTER TABLE solution_traitement ADD updated_by INT DEFAULT NULL, CHANGE maladie_id maladie_id INT DEFAULT NULL, CHANGE titre titre VARCHAR(200) DEFAULT NULL, CHANGE solution solution LONGTEXT DEFAULT NULL, CHANGE etapes etapes LONGTEXT DEFAULT NULL, CHANGE produits_recommandes produits_recommandes LONGTEXT DEFAULT NULL, CHANGE conseils_prevention conseils_prevention LONGTEXT DEFAULT NULL, CHANGE usage_count usage_count INT NOT NULL, CHANGE feedback_positive feedback_positive INT NOT NULL, CHANGE feedback_negative feedback_negative INT NOT NULL, CHANGE created_by created_by INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE solution_traitement ADD CONSTRAINT FK_375480F0B4B1C397 FOREIGN KEY (maladie_id) REFERENCES maladie (id_maladie) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE solution_traitement ADD CONSTRAINT FK_375480F0DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE solution_traitement ADD CONSTRAINT FK_375480F016FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_375480F0B4B1C397 ON solution_traitement (maladie_id)');
        $this->addSql('CREATE INDEX IDX_375480F0DE12AB56 ON solution_traitement (created_by)');
        $this->addSql('CREATE INDEX IDX_375480F016FE72E1 ON solution_traitement (updated_by)');
        $this->addSql('ALTER TABLE solution_traitement_vote ADD updated_at DATETIME DEFAULT NULL, ADD created_by INT NOT NULL, ADD updated_by INT DEFAULT NULL, CHANGE solution_traitement_id solution_traitement_id INT DEFAULT NULL, CHANGE utilisateur_id utilisateur_id INT DEFAULT NULL, CHANGE type type VARCHAR(8) DEFAULT NULL');
        $this->addSql('ALTER TABLE solution_traitement_vote ADD CONSTRAINT FK_59EA35418400BB71 FOREIGN KEY (solution_traitement_id) REFERENCES solution_traitement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE solution_traitement_vote ADD CONSTRAINT FK_59EA3541FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE solution_traitement_vote ADD CONSTRAINT FK_59EA3541DE12AB56 FOREIGN KEY (created_by) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE solution_traitement_vote ADD CONSTRAINT FK_59EA354116FE72E1 FOREIGN KEY (updated_by) REFERENCES utilisateurs (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_59EA35418400BB71 ON solution_traitement_vote (solution_traitement_id)');
        $this->addSql('CREATE INDEX IDX_59EA3541FB88E14F ON solution_traitement_vote (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_59EA3541DE12AB56 ON solution_traitement_vote (created_by)');
        $this->addSql('CREATE INDEX IDX_59EA354116FE72E1 ON solution_traitement_vote (updated_by)');
        $this->addSql('DROP INDEX uniq_sponsor_nom_secteur ON sponsors');
        $this->addSql('ALTER TABLE terrains DROP FOREIGN KEY `fk_terrains_categorie`');
        $this->addSql('DROP INDEX idx_terrains_categorie ON terrains');
        $this->addSql('ALTER TABLE terrains CHANGE description description LONGTEXT DEFAULT NULL, CHANGE adresse adresse LONGTEXT DEFAULT NULL, CHANGE caution caution NUMERIC(10, 2) NOT NULL, CHANGE disponible disponible TINYINT NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE terrains ADD CONSTRAINT FK_A7A03A42BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories (id)');
        $this->addSql('DROP INDEX IDX_D9F9A6ECB03A8386 ON user_notification');
        $this->addSql('ALTER TABLE user_notification DROP FOREIGN KEY `FK_D9F9A6ECE92F8F78`');
        $this->addSql('DROP INDEX idx_d9f9a6ece92f8f78 ON user_notification');
        $this->addSql('CREATE INDEX IDX_3F980AC8E92F8F78 ON user_notification (recipient_id)');
        $this->addSql('ALTER TABLE user_notification ADD CONSTRAINT `FK_D9F9A6ECE92F8F78` FOREIGN KEY (recipient_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateurs CHANGE adresse adresse LONGTEXT DEFAULT NULL, CHANGE type_user type_user VARCHAR(20) NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('DROP INDEX email ON utilisateurs');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497B315EE7927C74 ON utilisateurs (email)');
        $this->addSql('ALTER TABLE vehicules DROP FOREIGN KEY `fk_vehicules_categorie`');
        $this->addSql('DROP INDEX idx_vehicules_categorie ON vehicules');
        $this->addSql('DROP INDEX immatriculation ON vehicules');
        $this->addSql('ALTER TABLE vehicules CHANGE description description LONGTEXT DEFAULT NULL, CHANGE caution caution NUMERIC(10, 2) NOT NULL, CHANGE disponible disponible TINYINT NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE vehicules ADD CONSTRAINT FK_78218C2DBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categories (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE details_commandes DROP FOREIGN KEY FK_4FD424F782EA2E54');
        $this->addSql('ALTER TABLE details_commandes DROP FOREIGN KEY FK_4FD424F7806F0F5C');
        $this->addSql('DROP INDEX idx_4fd424f782ea2e54 ON details_commandes');
        $this->addSql('CREATE INDEX idx_details_commande ON details_commandes (commande_id)');
        $this->addSql('DROP INDEX idx_4fd424f7806f0f5c ON details_commandes');
        $this->addSql('CREATE INDEX idx_details_equipement ON details_commandes (equipement_id)');
        $this->addSql('ALTER TABLE details_commandes ADD CONSTRAINT FK_4FD424F782EA2E54 FOREIGN KEY (commande_id) REFERENCES commandes (id)');
        $this->addSql('ALTER TABLE details_commandes ADD CONSTRAINT FK_4FD424F7806F0F5C FOREIGN KEY (equipement_id) REFERENCES equipements (id)');
        $this->addSql('ALTER TABLE equipements DROP FOREIGN KEY FK_3F02D86BBCF5E72D');
        $this->addSql('ALTER TABLE equipements DROP FOREIGN KEY FK_3F02D86B670C757F');
        $this->addSql('ALTER TABLE equipements CHANGE description description TEXT DEFAULT NULL, CHANGE quantite_stock quantite_stock INT DEFAULT 0, CHANGE seuil_alerte seuil_alerte INT DEFAULT 5, CHANGE disponible disponible TINYINT DEFAULT 1, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE equipements ADD CONSTRAINT `fk_equipements_categorie` FOREIGN KEY (categorie_id) REFERENCES categories (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE equipements ADD CONSTRAINT `fk_equipements_fournisseur` FOREIGN KEY (fournisseur_id) REFERENCES fournisseurs (id) ON UPDATE CASCADE');
        $this->addSql('CREATE INDEX idx_equipements_categorie ON equipements (categorie_id)');
        $this->addSql('CREATE INDEX idx_equipements_fournisseur ON equipements (fournisseur_id)');
        $this->addSql('ALTER TABLE forum_moderation_alert DROP FOREIGN KEY FK_64949EBCDE12AB56');
        $this->addSql('ALTER TABLE forum_moderation_alert DROP FOREIGN KEY FK_64949EBC16FE72E1');
        $this->addSql('DROP INDEX IDX_64949EBCDE12AB56 ON forum_moderation_alert');
        $this->addSql('DROP INDEX IDX_64949EBC16FE72E1 ON forum_moderation_alert');
        $this->addSql('ALTER TABLE forum_moderation_alert DROP FOREIGN KEY FK_64949EBCBA9CD190');
        $this->addSql('ALTER TABLE forum_moderation_alert DROP FOREIGN KEY FK_64949EBCFB88E14F');
        $this->addSql('ALTER TABLE forum_moderation_alert CHANGE created_by created_by INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_64949ebcfb88e14f ON forum_moderation_alert');
        $this->addSql('CREATE INDEX IDX_9B2C69CFFB88E14F ON forum_moderation_alert (utilisateur_id)');
        $this->addSql('DROP INDEX idx_64949ebcba9cd190 ON forum_moderation_alert');
        $this->addSql('CREATE INDEX IDX_9B2C69CF1E8FDE0 ON forum_moderation_alert (commentaire_id)');
        $this->addSql('ALTER TABLE forum_moderation_alert ADD CONSTRAINT FK_64949EBCBA9CD190 FOREIGN KEY (commentaire_id) REFERENCES commentaire (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE forum_moderation_alert ADD CONSTRAINT FK_64949EBCFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP FOREIGN KEY FK_8D0F1179DE12AB56');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP FOREIGN KEY FK_8D0F117916FE72E1');
        $this->addSql('DROP INDEX IDX_8D0F1179DE12AB56 ON forum_post_bookmark');
        $this->addSql('DROP INDEX IDX_8D0F117916FE72E1 ON forum_post_bookmark');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP FOREIGN KEY FK_8D0F11794B89032C');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP FOREIGN KEY FK_8D0F1179FB88E14F');
        $this->addSql('ALTER TABLE forum_post_bookmark DROP updated_at, DROP created_by, DROP updated_by');
        $this->addSql('DROP INDEX idx_forum_post_bookmark_type ON forum_post_bookmark');
        $this->addSql('CREATE INDEX IDX_4B0E7C32C5F6B89B ON forum_post_bookmark (bookmark_type)');
        $this->addSql('DROP INDEX idx_forum_post_bookmark_post ON forum_post_bookmark');
        $this->addSql('CREATE INDEX IDX_4B0E7C324584665A ON forum_post_bookmark (post_id)');
        $this->addSql('DROP INDEX idx_forum_post_bookmark_user ON forum_post_bookmark');
        $this->addSql('CREATE INDEX IDX_4B0E7C32DB38439E ON forum_post_bookmark (utilisateur_id)');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD CONSTRAINT FK_8D0F11794B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_bookmark ADD CONSTRAINT FK_8D0F1179FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fournisseurs CHANGE adresse adresse TEXT DEFAULT NULL, CHANGE actif actif TINYINT DEFAULT 1, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY FK_17E64ABA50EAE44');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY FK_17E64ABA4A4A3511');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY FK_17E64ABA8A2D8B41');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY FK_17E64ABA4A4A3511');
        $this->addSql('ALTER TABLE locations DROP FOREIGN KEY FK_17E64ABA8A2D8B41');
        $this->addSql('ALTER TABLE locations CHANGE type_location type_location ENUM(\'vehicule\', \'terrain\') NOT NULL, CHANGE caution caution NUMERIC(10, 2) DEFAULT \'0.00\', CHANGE statut statut ENUM(\'en_attente\', \'confirmee\', \'en_cours\', \'terminee\', \'annulee\') DEFAULT \'en_attente\', CHANGE date_reservation date_reservation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE notes notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT `fk_locations_terrain` FOREIGN KEY (terrain_id) REFERENCES terrains (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT `fk_locations_utilisateur` FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT `fk_locations_vehicule` FOREIGN KEY (vehicule_id) REFERENCES vehicules (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX numero_location ON locations (numero_location)');
        $this->addSql('CREATE INDEX idx_locations_utilisateur ON locations (id_utilisateur)');
        $this->addSql('DROP INDEX idx_17e64aba8a2d8b41 ON locations');
        $this->addSql('CREATE INDEX idx_locations_terrain ON locations (terrain_id)');
        $this->addSql('DROP INDEX idx_17e64aba4a4a3511 ON locations');
        $this->addSql('CREATE INDEX idx_locations_vehicule ON locations (vehicule_id)');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT FK_17E64ABA4A4A3511 FOREIGN KEY (vehicule_id) REFERENCES vehicules (id)');
        $this->addSql('ALTER TABLE locations ADD CONSTRAINT FK_17E64ABA8A2D8B41 FOREIGN KEY (terrain_id) REFERENCES terrains (id)');
        $this->addSql('ALTER TABLE maladie DROP FOREIGN KEY FK_ADC4024BDE12AB56');
        $this->addSql('ALTER TABLE maladie DROP FOREIGN KEY FK_ADC4024B16FE72E1');
        $this->addSql('DROP INDEX IDX_ADC4024BDE12AB56 ON maladie');
        $this->addSql('DROP INDEX IDX_ADC4024B16FE72E1 ON maladie');
        $this->addSql('ALTER TABLE maladie DROP updated_by, CHANGE nom nom VARCHAR(150) NOT NULL, CHANGE created_by created_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE maladie_case DROP FOREIGN KEY FK_2D08B4F4B4B1C397');
        $this->addSql('ALTER TABLE maladie_case DROP FOREIGN KEY FK_2D08B4F4FB88E14F');
        $this->addSql('ALTER TABLE maladie_case DROP FOREIGN KEY FK_2D08B4F4DE12AB56');
        $this->addSql('ALTER TABLE maladie_case DROP FOREIGN KEY FK_2D08B4F416FE72E1');
        $this->addSql('DROP INDEX IDX_2D08B4F4B4B1C397 ON maladie_case');
        $this->addSql('DROP INDEX IDX_2D08B4F4FB88E14F ON maladie_case');
        $this->addSql('DROP INDEX IDX_2D08B4F4DE12AB56 ON maladie_case');
        $this->addSql('DROP INDEX IDX_2D08B4F416FE72E1 ON maladie_case');
        $this->addSql('ALTER TABLE maladie_case DROP created_by, DROP updated_by, CHANGE symptomes symptomes TEXT NOT NULL, CHANGE statut statut VARCHAR(30) NOT NULL, CHANGE maladie_id maladie_id INT NOT NULL, CHANGE utilisateur_id utilisateur_id INT NOT NULL');
        $this->addSql('ALTER TABLE maladie_case_photo DROP FOREIGN KEY FK_EA6003FBB59A4A');
        $this->addSql('ALTER TABLE maladie_case_photo DROP FOREIGN KEY FK_EA6003DE12AB56');
        $this->addSql('ALTER TABLE maladie_case_photo DROP FOREIGN KEY FK_EA600316FE72E1');
        $this->addSql('DROP INDEX IDX_EA6003FBB59A4A ON maladie_case_photo');
        $this->addSql('DROP INDEX IDX_EA6003DE12AB56 ON maladie_case_photo');
        $this->addSql('DROP INDEX IDX_EA600316FE72E1 ON maladie_case_photo');
        $this->addSql('ALTER TABLE maladie_case_photo DROP updated_at, DROP created_by, DROP updated_by, CHANGE filename filename VARCHAR(255) NOT NULL, CHANGE case_update_id case_update_id INT NOT NULL');
        $this->addSql('ALTER TABLE maladie_case_update DROP FOREIGN KEY FK_1254A170CF10D4F5');
        $this->addSql('ALTER TABLE maladie_case_update DROP FOREIGN KEY FK_1254A1701C0BE183');
        $this->addSql('ALTER TABLE maladie_case_update DROP FOREIGN KEY FK_1254A170DE12AB56');
        $this->addSql('ALTER TABLE maladie_case_update DROP FOREIGN KEY FK_1254A17016FE72E1');
        $this->addSql('DROP INDEX IDX_1254A170CF10D4F5 ON maladie_case_update');
        $this->addSql('DROP INDEX IDX_1254A1701C0BE183 ON maladie_case_update');
        $this->addSql('DROP INDEX IDX_1254A170DE12AB56 ON maladie_case_update');
        $this->addSql('DROP INDEX IDX_1254A17016FE72E1 ON maladie_case_update');
        $this->addSql('ALTER TABLE maladie_case_update DROP updated_at, DROP created_by, DROP updated_by, CHANGE resultat resultat VARCHAR(30) NOT NULL, CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE case_id case_id INT NOT NULL');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY FK_FDC6C6E88B13D439');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY FK_FDC6C6E850EAE44');
        $this->addSql('DROP INDEX IDX_FDC6C6E88B13D439 ON participations');
        $this->addSql('ALTER TABLE participations DROP FOREIGN KEY FK_FDC6C6E850EAE44');
        $this->addSql('ALTER TABLE participations CHANGE statut statut ENUM(\'en_attente\', \'confirme\', \'annule\') DEFAULT \'confirme\', CHANGE date_inscription date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE nombre_accompagnants nombre_accompagnants INT DEFAULT 0, CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE id_evenement id_evenement INT NOT NULL, CHANGE id_utilisateur id_utilisateur INT NOT NULL');
        $this->addSql('DROP INDEX idx_fdc6c6e850eae44 ON participations');
        $this->addSql('CREATE INDEX id_utilisateur ON participations (id_utilisateur)');
        $this->addSql('ALTER TABLE participations ADD CONSTRAINT FK_FDC6C6E850EAE44 FOREIGN KEY (id_utilisateur) REFERENCES utilisateurs (id)');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DFB88E14F');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DDE12AB56');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8D16FE72E1');
        $this->addSql('DROP INDEX IDX_5A8A6C8DDE12AB56 ON post');
        $this->addSql('DROP INDEX IDX_5A8A6C8D16FE72E1 ON post');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DFB88E14F');
        $this->addSql('ALTER TABLE post DROP created_at, DROP updated_at, DROP created_by, DROP updated_by, CHANGE contenu contenu TEXT NOT NULL, CHANGE categorie categorie VARCHAR(100) DEFAULT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT \'actif\'');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT `fk_post_utilisateur` FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_5a8a6c8dfb88e14f ON post');
        $this->addSql('CREATE INDEX fk_post_utilisateur ON post (utilisateur_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_reaction DROP FOREIGN KEY FK_1B3A8E56DE12AB56');
        $this->addSql('ALTER TABLE post_reaction DROP FOREIGN KEY FK_1B3A8E5616FE72E1');
        $this->addSql('DROP INDEX IDX_1B3A8E56DE12AB56 ON post_reaction');
        $this->addSql('DROP INDEX IDX_1B3A8E5616FE72E1 ON post_reaction');
        $this->addSql('ALTER TABLE post_reaction DROP created_at, DROP updated_at, DROP created_by, DROP updated_by');
        $this->addSql('ALTER TABLE solution_traitement DROP FOREIGN KEY FK_375480F0B4B1C397');
        $this->addSql('ALTER TABLE solution_traitement DROP FOREIGN KEY FK_375480F0DE12AB56');
        $this->addSql('ALTER TABLE solution_traitement DROP FOREIGN KEY FK_375480F016FE72E1');
        $this->addSql('DROP INDEX IDX_375480F0B4B1C397 ON solution_traitement');
        $this->addSql('DROP INDEX IDX_375480F0DE12AB56 ON solution_traitement');
        $this->addSql('DROP INDEX IDX_375480F016FE72E1 ON solution_traitement');
        $this->addSql('ALTER TABLE solution_traitement DROP updated_by, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE solution solution TEXT NOT NULL, CHANGE etapes etapes TEXT DEFAULT NULL, CHANGE produits_recommandes produits_recommandes TEXT DEFAULT NULL, CHANGE conseils_prevention conseils_prevention TEXT DEFAULT NULL, CHANGE usage_count usage_count INT DEFAULT 0 NOT NULL, CHANGE feedback_positive feedback_positive INT DEFAULT 0 NOT NULL, CHANGE feedback_negative feedback_negative INT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE maladie_id maladie_id INT NOT NULL, CHANGE created_by created_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE solution_traitement_vote DROP FOREIGN KEY FK_59EA35418400BB71');
        $this->addSql('ALTER TABLE solution_traitement_vote DROP FOREIGN KEY FK_59EA3541FB88E14F');
        $this->addSql('ALTER TABLE solution_traitement_vote DROP FOREIGN KEY FK_59EA3541DE12AB56');
        $this->addSql('ALTER TABLE solution_traitement_vote DROP FOREIGN KEY FK_59EA354116FE72E1');
        $this->addSql('DROP INDEX IDX_59EA35418400BB71 ON solution_traitement_vote');
        $this->addSql('DROP INDEX IDX_59EA3541FB88E14F ON solution_traitement_vote');
        $this->addSql('DROP INDEX IDX_59EA3541DE12AB56 ON solution_traitement_vote');
        $this->addSql('DROP INDEX IDX_59EA354116FE72E1 ON solution_traitement_vote');
        $this->addSql('ALTER TABLE solution_traitement_vote DROP updated_at, DROP created_by, DROP updated_by, CHANGE type type VARCHAR(8) NOT NULL, CHANGE solution_traitement_id solution_traitement_id INT NOT NULL, CHANGE utilisateur_id utilisateur_id INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_sponsor_nom_secteur ON sponsors (nom, secteur_activite)');
        $this->addSql('ALTER TABLE terrains DROP FOREIGN KEY FK_A7A03A42BCF5E72D');
        $this->addSql('ALTER TABLE terrains CHANGE description description TEXT DEFAULT NULL, CHANGE adresse adresse TEXT DEFAULT NULL, CHANGE caution caution NUMERIC(10, 2) DEFAULT \'0.00\', CHANGE disponible disponible TINYINT DEFAULT 1, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE terrains ADD CONSTRAINT `fk_terrains_categorie` FOREIGN KEY (categorie_id) REFERENCES categories (id) ON UPDATE CASCADE');
        $this->addSql('CREATE INDEX idx_terrains_categorie ON terrains (categorie_id)');
        $this->addSql('ALTER TABLE user_notification DROP FOREIGN KEY FK_3F980AC8E92F8F78');
        $this->addSql('CREATE INDEX IDX_D9F9A6ECB03A8386 ON user_notification (is_read)');
        $this->addSql('DROP INDEX idx_3f980ac8e92f8f78 ON user_notification');
        $this->addSql('CREATE INDEX IDX_D9F9A6ECE92F8F78 ON user_notification (recipient_id)');
        $this->addSql('ALTER TABLE user_notification ADD CONSTRAINT FK_3F980AC8E92F8F78 FOREIGN KEY (recipient_id) REFERENCES utilisateurs (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateurs CHANGE adresse adresse TEXT DEFAULT NULL, CHANGE type_user type_user ENUM(\'client\', \'admin\', \'technicien\') DEFAULT \'client\' NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX uniq_497b315ee7927c74 ON utilisateurs');
        $this->addSql('CREATE UNIQUE INDEX email ON utilisateurs (email)');
        $this->addSql('ALTER TABLE vehicules DROP FOREIGN KEY FK_78218C2DBCF5E72D');
        $this->addSql('ALTER TABLE vehicules CHANGE description description TEXT DEFAULT NULL, CHANGE caution caution NUMERIC(10, 2) DEFAULT \'0.00\', CHANGE disponible disponible TINYINT DEFAULT 1, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE vehicules ADD CONSTRAINT `fk_vehicules_categorie` FOREIGN KEY (categorie_id) REFERENCES categories (id) ON UPDATE CASCADE');
        $this->addSql('CREATE INDEX idx_vehicules_categorie ON vehicules (categorie_id)');
        $this->addSql('CREATE UNIQUE INDEX immatriculation ON vehicules (immatriculation)');
    }
}
